#! /usr/bin/bash


# Trivial tool to echo the weather as a single line thanks to https://wttr.in
# but also an excuse to remember that service, as well as some safe settings
# for shell scripting. Note: use shellcheck.
# If a failure happens, echo an empty string instead.

# Source: https://sipb.mit.edu/doc/safe-shell/ + manpage
# Exit immediately if a pipeline, a list, or a compound command,
# exits with a non-zero status.
set -e
# Treat unset variables and parameters other than the special parameters "@"
# and "*" as an error when performing parameter expansion. If expansion is
# attempted on an unset variable or parameter, the shell prints an error
# message, and, if not interactive, exits with a non-zero status.
set -u
# Disable pathname expansion.
set -f
# The return value of a pipeline is the value of the last (rightmost) command
# to exit with a non-zero status, or zero if all commands in the pipeline exit
# successfully. This option is disabled by default.
# There is no pipe in this script, but this is to save this as a "template".
set -o pipefail


CITY="${CITY:=Munich}"

WEATHER=$(curl --silent --fail "wttr.in/${CITY}?format=%c+%t+%w+%h")
STATUS=$?
if [ ${STATUS} -ne 0 ]; then
    exit ${STATUS}
fi
echo "${WEATHER}"
